/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImportRouteImport } from './routes/import'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestAttemptIdRouteImport } from './routes/test.$attemptId'
import { Route as ResultsAttemptIdRouteImport } from './routes/results.$attemptId'
import { Route as ConfigureSetIdRouteImport } from './routes/configure.$setId'

const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestAttemptIdRoute = TestAttemptIdRouteImport.update({
  id: '/test/$attemptId',
  path: '/test/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsAttemptIdRoute = ResultsAttemptIdRouteImport.update({
  id: '/results/$attemptId',
  path: '/results/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureSetIdRoute = ConfigureSetIdRouteImport.update({
  id: '/configure/$setId',
  path: '/configure/$setId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/configure/$setId': typeof ConfigureSetIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/test/$attemptId': typeof TestAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/configure/$setId': typeof ConfigureSetIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/test/$attemptId': typeof TestAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/configure/$setId': typeof ConfigureSetIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/test/$attemptId': typeof TestAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/import'
    | '/configure/$setId'
    | '/results/$attemptId'
    | '/test/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/import'
    | '/configure/$setId'
    | '/results/$attemptId'
    | '/test/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/import'
    | '/configure/$setId'
    | '/results/$attemptId'
    | '/test/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ImportRoute: typeof ImportRoute
  ConfigureSetIdRoute: typeof ConfigureSetIdRoute
  ResultsAttemptIdRoute: typeof ResultsAttemptIdRoute
  TestAttemptIdRoute: typeof TestAttemptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$attemptId': {
      id: '/test/$attemptId'
      path: '/test/$attemptId'
      fullPath: '/test/$attemptId'
      preLoaderRoute: typeof TestAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$attemptId': {
      id: '/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof ResultsAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure/$setId': {
      id: '/configure/$setId'
      path: '/configure/$setId'
      fullPath: '/configure/$setId'
      preLoaderRoute: typeof ConfigureSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ImportRoute: ImportRoute,
  ConfigureSetIdRoute: ConfigureSetIdRoute,
  ResultsAttemptIdRoute: ResultsAttemptIdRoute,
  TestAttemptIdRoute: TestAttemptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
