/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportRouteImport } from './routes/import'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestAttemptIdRouteImport } from './routes/test.$attemptId'
import { Route as ResultsAttemptIdRouteImport } from './routes/results.$attemptId'
import { Route as ConfigureSetIdRouteImport } from './routes/configure.$setId'
import { Route as AuthedSetsRouteImport } from './routes/_authed.sets'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestAttemptIdRoute = TestAttemptIdRouteImport.update({
  id: '/test/$attemptId',
  path: '/test/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsAttemptIdRoute = ResultsAttemptIdRouteImport.update({
  id: '/results/$attemptId',
  path: '/results/$attemptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureSetIdRoute = ConfigureSetIdRouteImport.update({
  id: '/configure/$setId',
  path: '/configure/$setId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSetsRoute = AuthedSetsRouteImport.update({
  id: '/sets',
  path: '/sets',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/sets': typeof AuthedSetsRoute
  '/configure/$setId': typeof ConfigureSetIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/test/$attemptId': typeof TestAttemptIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/sets': typeof AuthedSetsRoute
  '/configure/$setId': typeof ConfigureSetIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/test/$attemptId': typeof TestAttemptIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/import': typeof ImportRoute
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/sets': typeof AuthedSetsRoute
  '/configure/$setId': typeof ConfigureSetIdRoute
  '/results/$attemptId': typeof ResultsAttemptIdRoute
  '/test/$attemptId': typeof TestAttemptIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/login'
    | '/dashboard'
    | '/sets'
    | '/configure/$setId'
    | '/results/$attemptId'
    | '/test/$attemptId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/login'
    | '/dashboard'
    | '/sets'
    | '/configure/$setId'
    | '/results/$attemptId'
    | '/test/$attemptId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/import'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/sets'
    | '/configure/$setId'
    | '/results/$attemptId'
    | '/test/$attemptId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ImportRoute: typeof ImportRoute
  LoginRoute: typeof LoginRoute
  ConfigureSetIdRoute: typeof ConfigureSetIdRoute
  ResultsAttemptIdRoute: typeof ResultsAttemptIdRoute
  TestAttemptIdRoute: typeof TestAttemptIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$attemptId': {
      id: '/test/$attemptId'
      path: '/test/$attemptId'
      fullPath: '/test/$attemptId'
      preLoaderRoute: typeof TestAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$attemptId': {
      id: '/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof ResultsAttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure/$setId': {
      id: '/configure/$setId'
      path: '/configure/$setId'
      fullPath: '/configure/$setId'
      preLoaderRoute: typeof ConfigureSetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/sets': {
      id: '/_authed/sets'
      path: '/sets'
      fullPath: '/sets'
      preLoaderRoute: typeof AuthedSetsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedSetsRoute: typeof AuthedSetsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedSetsRoute: AuthedSetsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ImportRoute: ImportRoute,
  LoginRoute: LoginRoute,
  ConfigureSetIdRoute: ConfigureSetIdRoute,
  ResultsAttemptIdRoute: ResultsAttemptIdRoute,
  TestAttemptIdRoute: TestAttemptIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
